---
- name: Install apache files
  block:
    - name: insure that appache installed
      ansible.builtin.package:
        name: httpd
        state: present
      # where: "{{ ansible_os_family == 'RedHat' }}"
    # - name: insure that appache installed
    #   ansible.builtin.package:
    #     name: apache2
    #     state: present
    #   where: "{{ ansible_os_family == 'Debian' }}"
    - name: Copy sample index.php
      ansible.builtin.copy:
        src: index.php
        dest: /var/www/html/index.php
        mode: "0644"
      notify: Restart Apache
  rescue:
    - name: Handle Apache installation failure
      debug:
        msg: "Failed to install or configure Apache."

  always:
    - name: Ensure Apache service is running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
